### ISSUE TITLE
Visual Studio

### ISSUE THREAD

**Issue by maytho01** [LachieMorgatti/Tafe19S107#3]
Hey guys,
Can we cross check the WINDOWS 10 version we are using

We need to agree on what visual studio we are going use
Visual Studio 15
Visual Studio 17
Visual Studio 19

**Comment by MalcolmStudent** [comment]
I'm running Visual Studio 2017

**Comment by MalcolmStudent** [comment]
If you are having troubles I have found another website that could help out
https://www.hungryjacks.com.au/menu/whopper

**Comment by LachieMorgatti** [comment]
I'm in the same boat as @MalcolmStudent , I'm currently using Visual Studio 2017 and in the process of updating to Windows 10 version 1809.
