### ISSUE TITLE
Windows cant display the XAML

### ISSUE THREAD

**Issue by maytho01** [LachieMorgatti/Tafe19S107#4]
Hey guys, ive got a compatability issue with my windows 10
Visual Studio is telling me it requires 1809 ive only got 1803
im updating now to 1809, please do the same

https://www.microsoft.com/en-au/software-download/windows10

**Comment by MalcolmStudent** [comment]
Have you tried reinstalling windows?

**Comment by LachieMorgatti** [comment]
Updating to 1809 at the moment
