### ISSUE TITLE
Error with View List in Contact Details

### ISSUE THREAD

**Issue by MalcolmStudent** [LachieMorgatti/Tafe19S107#5]
Having an issue with my list view. the app runs smoothly with no errors and Visual Studio isn't showing up with any errors. The issues I'm having is when after the details into the Contact Details of the Insta_Richie app and hit save to but the information tho the database, the contact details aren't showing up in the list view below the text box fields. 

The information is being entered because I have a try catch to prevent null information from being into the database and if information that isn't there would throw up a message dialog warning that no information has been entered. But there are no warning boxes popping up.

Help Please

help please
![Error01](https://user-images.githubusercontent.com/48195731/56012056-c7e18a00-5d29-11e9-8b1c-a856bd8229e0.PNG)

![Error02](https://user-images.githubusercontent.com/48195731/56012057-c9ab4d80-5d29-11e9-8285-d96ae01cc88c.PNG)

**Comment by maytho01** [comment]
Hi Malcolm, I'm not sure about this but try changing the NotNull to unqiue on CustFName

ive got a sneaky feeling this could(nt) work

**Comment by LachieMorgatti** [comment]
If this is still an issue, could you provide screen shots of the code for the ListView? both XAML and C#

**Comment by MalcolmStudent** [comment]
Changing NotNull to unique has resolved my issue thank you
